# Generated by Django 3.2.9 on 2021-12-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_rename_img_movie_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imag',
            new_name='img',
        ),
    ]
